wandb_version: 1

CastToTensor:
  desc: null
  value: true
Learner:
  desc: null
  value:
    _name: <fastai.learner.Learner object at 0x7f40547e8c40>
    arch: torchvision.models.resnet.resnet18
    default_cbs: true
    loss_func:
      _name: FlattenedLoss of CrossEntropyLoss()
      axis: -1
      flatten: true
      floatify: false
      is_2d: true
    lr: 0.001
    metrics:
    - fastai.metrics.accuracy
    - fastai.metrics.error_rate
    - _name: <fastai.metrics.AccumMetric object at 0x7f40542e1940>
      activation: 'no'
      dim_argmax: -1
      flatten: true
      func: sklearn.metrics._classification.f1_score
      thresh: null
    - _name: <fastai.metrics.AccumMetric object at 0x7f40542e1ee0>
      activation: 'no'
      dim_argmax: -1
      flatten: true
      func: sklearn.metrics._classification.hamming_loss
      thresh: null
    model_dir: models
    moms:
    - 0.95
    - 0.85
    - 0.95
    n_out: 7
    normalize: true
    opt_func: fastai.optimizer.Adam
    path: .
    pretrained: true
    splitter: fastai.vision.learner._resnet_split
    train_bn: true
    wd: null
    wd_bn_bias: false
MixedPrecision:
  desc: null
  value: true
ParamScheduler:
  desc: null
  value: true
ProgressCallback:
  desc: null
  value: true
Recorder:
  desc: null
  value:
    add_time: true
    train_metrics: false
    valid_metrics: true
SaveModelCallback:
  desc: null
  value:
    at_end: false
    every_epoch: false
    fname: model
    with_opt: false
TrainEvalCallback:
  desc: null
  value: true
WandbCallback:
  desc: null
  value:
    dataset_name: null
    log: null
    log_dataset: false
    log_model: true
    log_preds: false
    log_preds_every_epoch: false
    model_name: null
    n_preds: 36
    reorder: true
    seed: 12345
    valid_dl: null
_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: fastai
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1675815947.440397
    t:
      1:
      - 1
      - 4
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 4
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.9.13
      5: 0.13.10
      8:
      - 5
arch:
  desc: null
  value: resnet18
augment:
  desc: null
  value: true
batch per epoch:
  desc: null
  value: 58
batch size:
  desc: null
  value: 4
batch_size:
  desc: null
  value: 4
dataset.tfms:
  desc: null
  value: '[Pipeline: ColReader -- {''cols'': ''image_fname'', ''pref'': '''', ''suff'':
    '''', ''label_delim'': None} -> PILBase.create, Pipeline: ColReader -- {''cols'':
    ''label'', ''pref'': '''', ''suff'': '''', ''label_delim'': None} -> Categorize
    -- {''vocab'': None, ''sort'': True, ''add_na'': False}]'
device:
  desc: null
  value: cuda
dls.after_batch:
  desc: null
  value: "Pipeline: IntToFloatTensor -- {'div': 255.0, 'div_mask': 1} -> Flip -- {'size':\
    \ None, 'mode': 'bilinear', 'pad_mode': 'reflection', 'mode_mask': 'nearest',\
    \ 'align_corners': True, 'p': 0.5} -> Brightness -- {'max_lighting': 0.2, 'p':\
    \ 1.0, 'draw': None, 'batch': False} -> Normalize -- {'mean': tensor([[[[0.4850]],\n\
    \n         [[0.4560]],\n\n         [[0.4060]]]], device='cuda:0'), 'std': tensor([[[[0.2290]],\n\
    \n         [[0.2240]],\n\n         [[0.2250]]]], device='cuda:0'), 'axes': (0,\
    \ 2, 3)}"
dls.after_item:
  desc: null
  value: 'Pipeline: Resize -- {''size'': (240, 240), ''method'': ''crop'', ''pad_mode'':
    ''reflection'', ''resamples'': (<Resampling.BILINEAR: 2>, <Resampling.NEAREST:
    0>), ''p'': 1.0} -> ToTensor'
dls.before_batch:
  desc: null
  value: 'Pipeline: '
epochs:
  desc: null
  value: 10
framework:
  desc: null
  value: fastai
frozen:
  desc: null
  value: true
frozen idx:
  desc: null
  value: 2
img_size:
  desc: null
  value: 240
input 1 dim 1:
  desc: null
  value: 4
input 1 dim 2:
  desc: null
  value: 3
input 1 dim 3:
  desc: null
  value: 240
input 1 dim 4:
  desc: null
  value: 240
log_preds:
  desc: null
  value: false
lr:
  desc: null
  value: 0.00010442418871204876
mixed_precision:
  desc: null
  value: true
model parameters:
  desc: null
  value: 11707456
n_inp:
  desc: null
  value: 1
pretrained:
  desc: null
  value: true
seed:
  desc: null
  value: 42
